export const AUDIT_ACTION_TYPES = [
  'STUDENT_CREATED',
  'STUDENT_UPDATED',
  'STUDENT_STATUS_CHANGED',
  'STUDENT_DELETED',
  'STUDENT_ATTENDANCE_EDITED',
  'PAYMENT_REQUEST_CREATED',
  'PAYMENT_REQUEST_UPDATED',
  'PAYMENT_REQUEST_CANCELLED',
  'PAYMENT_REQUEST_APPROVED',
  'PAYMENT_REQUEST_REJECTED',
  'STAFF_ATTENDANCE_CHANGED',
  'MONTHLY_DUES_ENGINE_RAN',
  'EXPENSE_CREATED',
  'EXPENSE_UPDATED',
  'EXPENSE_DELETED',
  'PARENT_INVITED',
  'PARENT_ACTIVATED',
  'FEE_PAYMENT_INITIATED',
  'FEE_PAYMENT_COMPLETED',
  'FEE_PAYMENT_FAILED',
  'EVENT_CREATED',
  'EVENT_UPDATED',
  'EVENT_DELETED',
] as const;
export type AuditActionType = (typeof AUDIT_ACTION_TYPES)[number];

export const AUDIT_ENTITY_TYPES = [
  'STUDENT',
  'STUDENT_ATTENDANCE',
  'PAYMENT_REQUEST',
  'STAFF_ATTENDANCE',
  'FEE_DUE',
  'EXPENSE',
  'PARENT_STUDENT_LINK',
  'FEE_PAYMENT',
  'EVENT',
] as const;
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];
